[package]
name = "rusturn"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
slog = "1"
rustun = "0.1"
fibers = "0.1"
futures = "0.1"
trackable = "0.1"

[dev-dependencies]
clap = "2"
slog-term = "1"